// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUJreGDIJ_AkUeidNZgIov5-PK2VnyfJo',
    appId: '1:850734062900:web:e1fb5b7f88e4d82a51d961',
    messagingSenderId: '850734062900',
    projectId: 'brainvent-9704a',
    authDomain: 'brainvent-9704a.firebaseapp.com',
    storageBucket: 'brainvent-9704a.firebasestorage.app',
    measurementId: 'G-1C4E3302FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMc3ReblVTqLb1dr2f7VbaZvQ9lDiadng',
    appId: '1:850734062900:android:ea09f96ad1367bf151d961',
    messagingSenderId: '850734062900',
    projectId: 'brainvent-9704a',
    storageBucket: 'brainvent-9704a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWc-bL8obrFz1iwyT-tcmnDRsJOBKv-jg',
    appId: '1:850734062900:ios:e5f902cbf7d40cac51d961',
    messagingSenderId: '850734062900',
    projectId: 'brainvent-9704a',
    storageBucket: 'brainvent-9704a.firebasestorage.app',
    iosBundleId: 'com.brainvent.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWc-bL8obrFz1iwyT-tcmnDRsJOBKv-jg',
    appId: '1:850734062900:ios:67791c77de0fc60251d961',
    messagingSenderId: '850734062900',
    projectId: 'brainvent-9704a',
    storageBucket: 'brainvent-9704a.firebasestorage.app',
    iosBundleId: 'com.example.dumpitMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUJreGDIJ_AkUeidNZgIov5-PK2VnyfJo',
    appId: '1:850734062900:web:3673e842d6d96b7b51d961',
    messagingSenderId: '850734062900',
    projectId: 'brainvent-9704a',
    authDomain: 'brainvent-9704a.firebaseapp.com',
    storageBucket: 'brainvent-9704a.firebasestorage.app',
    measurementId: 'G-70D5LWQ2SD',
  );
}
